services:
  kafka-ui: 
    container_name: kafka-ui 
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8085:8080
    environment:
      # KAFKA_CLUSTERS_0_NAME: kafka-0
      # KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-1:29091
      # KAFKA_CLUSTERS_0_METRICS_PORT: 19101
      # KAFKA_CLUSTERS_1_NAME: kafka-1
      # KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: broker-2:29092
      # KAFKA_CLUSTERS_1_METRICS_PORT: 19102
      # KAFKA_CLUSTERS_2_NAME: kafka-2
      # KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: broker-3:29093
      # KAFKA_CLUSTERS_2_METRICS_PORT: 19103
      DYNAMIC_CONFIG_ENABLED: 'true'
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "1m"
    # volumes:
    #   - ./config.yml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true