version: '3.8'

services:
  kafka:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "9092:9092"
      # - "29092:29092"
      - "9093:9093"
    environment:
      # KRaft settings
      - KAFKA_CFG_BROKER_ID=${BROKER_ID}
      - KAFKA_CFG_NODE_ID=${NODE_ID}
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # maps node IDs to their respective addresses and ports for communication
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@${KAFKA_0}:9093,1@${KAFKA_1}:9093,2@${KAFKA_2}:9093
      - KAFKA_KRAFT_CLUSTER_ID=${CLUSTER_ID}

      # Listeners
      # defines the addresses the Kafka node listens on
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # specifies the addresses that will be passed on to clients to connect to the node
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_0}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # number of cluster nodes multiple by two
      - KAFKA_CFG_NUM_PARTITIONS=${PARTITION_NUMBER}

      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=${TOPIC_REPLICATION_FACTOR}
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=${LOG_REPLICATION_FACTOR}
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=${LOG_MIN_ISR}
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - kafka-network

volumes:
  kafka_data:
    driver: local

networks:
  kafka-network:
    external: true