version: '3'
  
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    restart: always
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: <server_ip_address>
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "stream-action"
  kafka-ui:
    container_name: kafka-ui
    image: consdata/kouncil:latest
    restart: always
    ports:
      - 8500:8080
    environment:
      bootstrapServers: kafka:9092
      kouncil.auth.active-provider: inmemory
